### ISSUE TITLE
Scribe on Artifact Hub

### ISSUE THREAD

**Issue by cooktheryan** [backube/scribe#105]
**Describe the feature you'd like to have.**
With the 0.1 release it would be nice to be able to install via helm hub

**What is the value to the end user? (why is it a priority?)**
Ease of installation

**How will we know we have a good solution? (acceptance criteria)**
Project is available for others to install via artifact hub

**Additional context**

**Comment by JohnStrunk** [comment]
As soon as we create the release, I can add the chart to the [Backube chart repo](https://github.com/backube/helm-charts), and Artifact Hub should pick it up.

**Comment by cooktheryan** [comment]
very cool!
