### ISSUE TITLE
split testing and test 1.21

### ISSUE THREAD

**Issue by cooktheryan** [backube/scribe#158]
**Describe the feature you'd like to have.**
I would like to test 1.20 and 1.21

**What is the value to the end user? (why is it a priority?)**
Ensures all versions work

**How will we know we have a good solution? (acceptance criteria)**
testing for multiple versions is available

**Additional context**

**Comment by JohnStrunk** [comment]
Looks like kind 0.11 is out, bringing support for 1.21.
