### ISSUE TITLE
e2e tests

### ISSUE THREAD

**Issue by cooktheryan** [backube/scribe#28]
**Describe the feature you'd like to have.**
Automated e2e testing

**What is the value to the end user? (why is it a priority?)**
Ensure updates and features will no break new installations

**How will we know we have a good solution? (acceptance criteria)**
code will be required to pass ci

**Additional context**

**Comment by JohnStrunk** [comment]
GH actions can create the cluster (matrix), but we need something to actually run scenarios against the operator.
Perhaps we can use [kuttl](https://kuttl.dev/docs/kuttl-test-harness.html#writing-your-first-test) for this.

**Comment by screeley44** [comment]
https://kuttl.dev/docs/kuttl-test-harness.html#writing-your-first-test
