### ISSUE TITLE
rsync destination needs a timeout

### ISSUE THREAD

**Issue by cooktheryan** [backube/scribe#35]
**Describe the feature you'd like to have.**
The destination needs to have the job stopped permanently if a timer is exceeded. The reason this is required is to ensure primary site does not come back online and resume rsync functionality and destroy data at the failover site which would currently be the active site.

**What is the value to the end user? (why is it a priority?)**
high priority as it ensures the data on the non active side does not destroy data on the active side

**How will we know we have a good solution? (acceptance criteria)**
Stop primary side, allow failover applications to start, and bring primary side online and ensure that data is not sent to failover location.

**Additional context**

**Comment by cooktheryan** [comment]
@JohnStrunk @screeley44 wanted to get your take on this but I believe I have a solution mapped out in my head already. We don't really have a split brain option to keep us safe like we did with ceph

**Comment by JohnStrunk** [comment]
I think this is only a concern if the destination is using copymethod none.

If it's using snapshot, the live pv on the destination is different from the one being used as the replication destination.

To handle the none case, we could add a disabled Boolean to the destination cr that the admin could toggle to prevent incoming replication. Having this would also allow us to return an error to the source of it tries to sync. Then the source could tell the difference between disabled and down.

**Comment by cooktheryan** [comment]
:+1: 

I'll leave this open to handle the None method but it sound like the more advanced features that we want to use besides None are already good

**Comment by JohnStrunk** [comment]
Closing this since #60 is our solution. If you think there's more, feel free to reopen.
