### ISSUE TITLE
kubectl plugin

### ISSUE THREAD

**Issue by JohnStrunk** [backube/scribe#42]
**Describe the feature you'd like to have.**
It would be good to have a [kubectl plugin](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/) for scribe to help with routine tasks that require interesting incantations today.

**What is the value to the end user? (why is it a priority?)**
As users evaluate Scribe, their experience will be shaped by how easy/difficult it is to use. Today, we have some things that are a bit complicated, like linking the source and destination for rsync (copying the secret from one to another). Perhaps a kubectl plugin could help make this easier.

**How will we know we have a good solution? (acceptance criteria)**
* There should be a set of `kubectl scribe ...` commands that help users interact with Scribe
  * It should allow users to more easily "state what they want" without overly worrying about the yaml syntax

**Additional context**
I've opened this issue just to track it. The first step here should be figuring out if this is even worthwhile.

**Comment by JohnStrunk** [comment]
I think @sallyom is looking into this

**Comment by sallyom** [comment]
`$ kubectl scribe` exists!
(so does `$ oc scribe`)

I believe this issue can be closed/resolved.
