### ISSUE TITLE
document replication options

### ISSUE THREAD

**Issue by cooktheryan** [backube/scribe#43]
**Describe the feature you'd like to have.**
I would like to know what options are available at source and destination to properly choose which one to use.

**What is the value to the end user? (why is it a priority?)**
More information on properly using scribe

**How will we know we have a good solution? (acceptance criteria)**

**Additional context**

**Comment by JohnStrunk** [comment]
Broadening the scope of this issue a bit based on today's meeting:
- [Configuration and CRDs](https://scribe-replication.readthedocs.io/en/latest/design/custom-resources.html) still has the original CRD design.
- [Rsync-based data mover](https://scribe-replication.readthedocs.io/en/latest/design/mover-rsync.html) design needs a few fixups to be consistent with how it actually works. I'm thinking small edits here (keeping it high-level) with usage docs going elsewhere.
- We should examine the two "getting started" pages. There isn't really much difference between OCP and kube. Perhaps the OpenShift-specific stuff can just be inline notes.
- I'd like to get actual usage docs started... Documenting the CR options for Rsync & Rclone. I'm definitely open to ideas how to organize this--- by rsync/rclone or by use case (i.e., async replicate a volume leads to rsync config; distribute data to secondary clusters leads to rclone)
- The top-level docs page needs some intro and pointers of where to go next: Install -> usage
