### ISSUE TITLE
split getting started to support rclone and rsync

### ISSUE THREAD

**Issue by cooktheryan** [backube/scribe#61]
**Describe the feature you'd like to have.**
Depending on what user wants to test out during getting started. The section should be broken out to allow for quickly accessing the directions they need

**What is the value to the end user? (why is it a priority?)**
Ease of use

**How will we know we have a good solution? (acceptance criteria)**
Review of directions by another user

**Additional context**

**Comment by JohnStrunk** [comment]
Probably related to #43
