### ISSUE TITLE
Generate an error if more than one of rsync, rclone, or external are specified

### ISSUE THREAD

**Issue by JohnStrunk** [backube/scribe#80]
**Describe the bug**
A Replication* object is meant on only have one method specified (rsync, rclone, or external). Right now, no error is generated if multiple are specified. Instead the code just picks one and ignores the others.

**Steps to reproduce**
* Specify multiple replication methods in a single Replication CR
* Note that no error is generated

**Expected behavior**
It should be an error, with a proper message added to the `.status` field

**Actual results**

**Additional context**
From discussion on #63 
cc @jeffvance

**Comment by cooktheryan** [comment]
resolved in #97
