### ISSUE TITLE
Consider restic as an additional data mover

### ISSUE THREAD

**Issue by JohnStrunk** [backube/scribe#89]
**Describe the feature you'd like to have.**
Add [restic](https://restic.readthedocs.io/) as a data mover in addition to rsync & rclone.

**What is the value to the end user? (why is it a priority?)**
* Some scenarios could benefit from the multi-version capabilities of restic.
* Restic saves the file attributes (unlike rclone)
* This could make Scribe useful as a data-only backup utility for scenarios where the kube resources are managed elsewhere (e.g., gitops)

**How will we know we have a good solution? (acceptance criteria)**

**Additional context**
* I wonder if restic could supersede rclone for 1:n replication... Restic locks the repository for some operations, so the lack of parallelism may be a problem.
* We'd need to experiment w/ preserving (best-effort) the restic cache to speed scanning for incrementals
* We'd need a strategy for pruning the repository also

**Comment by mykaul** [comment]
Interesting to see that Restic has rclone as a backend...

**Comment by JohnStrunk** [comment]
With the docs in #185, I think we can close this.
